name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-producer:
    name: Build Go Producer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
      
      - name: Build
        run: |
          cd producer
          go build -v .
      
  lint:
    name: Lint Go Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v8

      - name: Run lint
        run: |
          cd producer
          golangci-lint run