name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-producer:
    name: Build Go Producer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      
      - name: Build
        run: |
          cd producer
          go build -v .
      
  lint:
    name: Lint Go Code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: producer  # run all steps from inside producer/

    steps:
      - uses: actions/checkout@v4

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.55.2
          args: --timeout=2m --out-format=colored-line-number

      - name: Run golangci-lint
        run: golangci-lint run ./...